---
title: "PBSMapping Intro"
output: html_notebook
---


```{r envr}
library(PBSmapping)
library(tidyverse)
```

```{r fig 7 tows}
.PBSfig07 <- function() {  # towTracks from Longspine Thornyhead Survey
  clr <- .PBSclr();    
  data(nepacLL,towTracks,towData,envir=sys.frame(sys.nframe()));    # add a colour column 'col' to 'towData'    
  pdata  <- towData;  
  pdata$Z <- pdata$dep    
  pdata  <- makeProps(pdata, breaks=c(500,800,1200,1600), 
                      "col",                        
                      c(clr$black, clr$red, clr$blue))    
  par(mfrow=c(1,1),omi=c(0,0,0,0))
  
  #------Plot-the-figure------    
  plotMap(nepacLL, 
          col=clr$land, 
          bg=clr$sea, 
          xlim=c(-127.8,-125.5),
          ylim=c(48,49.8),       
          tck=-0.01, 
          mgp=c(2,.5,0), 
          cex=1.2,
          plt=c(.08,1,.08,.98))    
  addLines(towTracks, 
           polyProps=pdata, 
           lwd=3)    # right-justify the legend labels    
  temp <- legend(x=-127.6, y=48.4, 
                 legend=c(" "," "," "), 
                 lwd=3, 
                 bty="n",       
                 text.width=strwidth("1200-1600 m"), 
                 col=c(clr$black,clr$red,clr$blue))
  text(temp$rect$left+temp$rect$w, 
       temp$text$y,       
       c("500-800 m", 
         "800-1200 m", 
         "1200-1600 m"), 
       pos=2)
  text(temp$rect$left+temp$rect$w/2,
       temp$rect$top,
       pos=3,
       "LTS Survey Tracks");
  text(-125.6,49.7,
       "Vancouver\nIsland",
       cex=1.2,
       adj=1)    
  box()  
  } 
.PBSfig07()
```
Fig 7 didn't work because we don't have an equivalent to towTracks

```{r fig 09}
.PBSfig09 <- function() {  
  # combineEvents in Queen Charlotte Sound    
  clr <- .PBSclr();     
  data(nepacLL,surveyData,envir=sys.frame(sys.nframe()));    
  events <- surveyData    
  xl     <- c(-131.8, -127.2);  
  yl <- c(50.5, 52.7)    
  # prepare EventData; clip it, omit NA entries, and calculate CPUE    
  events <- events[events$X >= xl[1] & events$X <= xl[2] &                     
                     events$Y >= yl[1] & events$Y <= yl[2], ]    
  events <- na.omit(events)    
  events$cpue <- events$catch/(events$effort/60)    
  # make a grid for the Queen Charlotte Sound    
  grid   <- makeGrid(x=seq(-131.6,-127.6,.1), 
                     y=seq(50.6,52.6,.1),                     
                     projection="LL", 
                     zone=9)    
  # locate EventData in grid    
  locData<- findCells(events, grid)    
  events$Z <- events$cpue    
  pdata  <- combineEvents(events, locData, FUN=mean)    
  brks   <- c(0,50,300,750,1500,25000); 
  lbrks <- length(brks)    
  cols   <- c(clr$lettuce, clr$moss, clr$irish, clr$forest, clr$black)   
  pdata  <- makeProps(pdata, brks, "col", cols)    
  par(mfrow=c(1,1),omi=c(0,0,0,0)) 
  #------Plot-the-figure------    
  plotMap(nepacLL, 
          col=clr$land, 
          bg=clr$sea, 
          xlim=xl, 
          ylim=yl, 
          tck=-0.015,            
          mgp=c(2,.5,0), 
          cex=1.2, 
          plt=c(.08,.98,.08,.98))    
  addPolys(grid, polyProps=pdata)    
  for (i in 1:nrow(events)) {       
    # plot one point at a time for clarity       
    points(events$X[i], 
           events$Y[i], 
           pch=16,
           cex=0.50,
           col=clr$white)       
    points(events$X[i], 
           events$Y[i], 
           pch=1, 
           cex=0.55,
           col=clr$black) 
    }    
  yrtxt  <- paste("(",min(events$year),"-",                 
                  substring(max(events$year),3),")",sep="")    
  text(xl[1]+.5,
       yl[2]-.1,
       c("POP Surveys", yrtxt),
       cex=1.2,
       adj=0)    
  # add a legend; right-justify the legend labels  
  temp <- legend(x=xl[1]+.3, 
                 y=yl[1]+.7, 
                 legend = rep(" ", 5),               
                 text.width=strwidth("1500 - 25000"), 
                 bty="n", 
                 fill=cols)    
  text(temp$rect$left + temp$rect$w, 
       temp$text$y, 
       pos=2,         
       paste(brks[1:(lbrks-1)],
             brks[2:lbrks], 
             sep=" - "))
  text(temp$rect$left+temp$rect$w/2,
       temp$rect$top,pos=3,
       "CPUE (kg/h)",
       cex=1);  
} 
.PBSfig09()
```

```{r fig.height=16, fig.width=12}
#makin_plots <- function() {    
setup_catch <- read_csv("data/data2/Shelf_Flatfish_Haul_Catch.csv", guess_max = 10000)
setup_catch <- setup_catch %>%
  filter(CRUISE>= 199999 & CRUISE<201900,
         REGION=="BS", 
         START_LATITUDE<65) %>%
  mutate(YEAR=floor((CRUISE/100)))
setup_catch <- setup_catch %>% mutate(EID = seq(1:nrow(setup_catch)))
colnames(setup_catch)[14] <- "Y"
colnames(setup_catch)[16] <- "X"
#colnames(setup_catch)[1] <- "EID"





clr <- .PBSclr();
  data(nepacLL, envir=sys.frame(sys.nframe()));    # not a clue what this does
  events <- as.EventData(setup_catch, projection = "LL", zone=3)   
  xl     <- c(-179, -157.9);  #unnecessary
  yl <- c(54.1, 65.1)    #unnecessary
  # prepare EventData; clip it, omit NA entries, and calculate CPUE    
  # events <- events[events$STARTING_LONGITUDE >= xl[1] & events$STARTING_LONGITUDE <= xl[2] &        #unnecessary             
  #                    events$STARTING_LATITUDE >= yl[1] & events$STARTING_LATITUDE <= yl[2], ]    # unnecessary
  #events <- na.omit(events)   # would probably break things
  #events$cpue <- events$catch/(events$effort/60)    
  # make a grid   
  grid_pbs   <- makeGrid(x=seq(-179, -157.9,.5), 
                     y=seq(54.1, 65.1,.5),                     
                     projection="LL", 
                     zone=3)    # UTM Zones, Bering Sea is 1-4
  # locate EventData in grid    
  locData<- findCells(events, grid_pbs)    
  events$Z <- events$GEAR_TEMPERATURE    
  pdata  <- combineEvents(events, locData, FUN=mean)    
  brks   <- c(-1.7,1.4,4.5,7.5,10.7,13.8); 
  lbrks <- length(brks)    
  cols   <- c(clr$lettuce, clr$moss, clr$irish, clr$forest, clr$black)    #colors 
  pdata  <- makeProps(pdata, brks, "col", cols)    
  par(mfrow=c(1,1),omi=c(0,0,0,0)) 
  #------Plot-the-figure------    
  plotMap(nepacLL, 
          col=clr$land, 
          bg=clr$sea, 
          xlim=xl, 
          ylim=yl, 
          tck=-0.015,            
          mgp=c(2,.5,0), 
          cex=1.2, 
          plt=c(.08,.98,.08,.98))    
  addPolys(grid_pbs, polyProps=pdata)    
  for (i in 1:nrow(events)) {       
    # plot one point at a time for clarity       
    points(events$X[i], 
           events$Y[i], 
           pch=16,
           cex=0.50,
           col=clr$white)       
    points(events$X[i], 
           events$Y[i], 
           pch=1, 
           cex=0.55,
           col=clr$black) 
    }    
  yrtxt  <- paste("(",min(events$YEAR),"-",                 
                  substring(max(events$YEAR),3),")",sep="")    
  text(xl[1]+.5,
       yl[2]-.1,
       c("POP Surveys", yrtxt),
       cex=1.2,
       adj=0)    
  # add a legend; right-justify the legend labels  
  temp <- legend(x=xl[1]+1, 
                 y=yl[1]+2, 
                 legend = rep(" ", 5),               
                 text.width=strwidth("1500 - 25000"), 
                 bty="n", 
                 fill=cols)    
  text(temp$rect$left + temp$rect$w, 
       temp$text$y, 
       pos=2,         
       paste(brks[1:(lbrks-1)],
             brks[2:lbrks], 
             sep=" - "))
  text(temp$rect$left+temp$rect$w/2,
       temp$rect$top,pos=3,
       "Temps",
       cex=1);  
#} 
#makin_plots()
```

```{r fig.height=16, fig.width=12}
# data -------------------------------------------------------------------------
# setup_catch <- read_csv("data/data2/Shelf_Flatfish_Haul_Catch.csv", guess_max = 10000)
# setup_catch <- setup_catch %>%
#   filter(CRUISE>= 199999 & CRUISE<201900,
#          REGION=="BS", 
#          START_LATITUDE<65) %>%
#   mutate(YEAR=floor((CRUISE/100)))
# setup_catch <- setup_catch %>% mutate(EID = seq(1:nrow(setup_catch)))
# colnames(setup_catch)[14] <- "Y"
# colnames(setup_catch)[16] <- "X"
#colnames(setup_catch)[1] <- "EID" doesn't work to change 
# function ---------------------------------------------------------------------
makin_plots <- function() { 
  clr <- .PBSclr(); # load color scheme
  data(nepacLL, envir=sys.frame(sys.nframe())); # load map data
  events <- as.EventData(setup_catch, projection = "LL", zone=3)  #make catch data event data
  # make bounding box
  xl <- c(-179, -157.9); 
  yl <- c(54.1, 65.1)
  # create grid
  grid_pbs   <- makeGrid(x=seq(-179, -157.9,.5), y=seq(54.1, 65.1,.5),                     
                     projection="LL", zone=3)    # UTM Zones, Bering Sea is 1-4
  # find Event Data (hauls) in grid and calculate means
  locData<- findCells(events, grid_pbs) 
  events$Z <- events$GEAR_TEMPERATURE # gear_temp is simple to start with  
  pdata  <- combineEvents(events, locData, FUN=mean) # summarise step
   # set breakpoints in temps and assign colors
  brks   <- c(-1.7,1.4,4.5,7.5,10.7,13.8);
  lbrks <- length(brks)    
  cols   <- c(clr$lettuce, clr$moss, clr$irish, clr$forest, clr$black) #assign colors to groups
  pdata  <- makeProps(pdata, brks, "col", cols) # append colors column   
  par(mfrow=c(1,1),omi=c(0,0,0,0)) 
  #------Plot-the-figure------    
  plotMap(nepacLL, 
          col=clr$land, 
          bg=clr$sea, 
          xlim=xl, 
          ylim=yl, 
          tck=-0.015,            
          mgp=c(2,.5,0), 
          cex=1.2, 
          plt=c(.08,.98,.08,.98))    
  addPolys(grid_pbs, polyProps=pdata)    
  for (i in 1:nrow(events)) {       
    # plot one point at a time for clarity (seems slow?)      
    points(events$X[i], 
           events$Y[i], 
           pch=16,
           cex=0.50,
           col=clr$white)       
    points(events$X[i], 
           events$Y[i], 
           pch=1, 
           cex=0.55,
           col=clr$black) 
  }
  # title
  yrtxt  <- paste("(",min(events$YEAR),"-",                 
                  substring(max(events$YEAR),3),")",sep="")    
  text(xl[1]+0.1,
       yl[2]-1,
       c("Eastern Bering Sea Hauls\n\n\n", yrtxt),
       cex=1.2,
       adj=0)    
  # add a legend; right-justify the legend labels  
  temp <- legend(x=xl[1]+1, 
                 y=yl[1]+2, 
                 legend = rep(" ", 5),               
                 text.width=strwidth("-1.7 to 13.8 degrees C"), 
                 bty="n", 
                 fill=cols)    
  text(temp$rect$left + temp$rect$w, 
       temp$text$y, 
       pos=2,         
       paste(brks[1:(lbrks-1)],
             brks[2:lbrks], 
             sep=" - "))
  text(temp$rect$left+temp$rect$w/2,
       temp$rect$top,pos=3,
       "Gear Temperatures",
       cex=1);  
}
# call -------------------------------------------------------------------------
makin_plots()
```

```{r, fig.height=14, fig.width=10}
# data -------------------------------------------------------------------------
setup_catch <- read_csv("data/data2/Shelf_Flatfish_Haul_Catch.csv", guess_max = 10000)
setup_catch <- setup_catch %>%
  filter(CRUISE>= 199999 & CRUISE<201900,
         REGION=="BS",
         START_LATITUDE<65) %>%
  mutate(YEAR=floor((CRUISE/100)))
setup_catch <- setup_catch %>% mutate(EID = seq(1:nrow(setup_catch)))
colnames(setup_catch)[14] <- "Y"
colnames(setup_catch)[16] <- "X"
#colnames(setup_catch)[1] <- "EID" doesn't work to change 
# function ---------------------------------------------------------------------
makin_plots_dos <- function() { 
  clr <- .PBSclr(); # load color scheme
  data(nepacLL, envir=sys.frame(sys.nframe())); # load map data
  events <- as.EventData(setup_catch, projection = "LL", zone=3)  #make catch data event data
  # make bounding box
  xl <- c(-179, -157.9); 
  yl <- c(54.1, 65.1)
  # create grid
  grid_pbs   <- makeGrid(x=seq(-179, -157.9,1), y=seq(54.1, 65.1,1),                     
                     projection="LL", zone=3)    # UTM Zones, Bering Sea is 1-4
  # find Event Data (hauls) in grid and calculate means
  locData<- findCells(events, grid_pbs) 
  events$Z <- events$GEAR_TEMPERATURE # gear_temp is simple to start with 
  # events <- na.omit(events)
  pdata  <- combineEvents(events, locData, FUN=mean,na.rm=TRUE) # summarise step
   # set breakpoints in temps and assign colors
  brks   <- c(-1.6,1.4,4.5,7.5,10.7,13.9);
  lbrks <- length(brks)    
  cols   <- c(clr$lettuce, clr$moss, clr$irish, clr$forest, clr$black) #assign colors to groups
  pdata  <- makeProps(pdata, brks, "col", cols) # append colors column   
  par(mfrow=c(1,1),omi=c(0,0,0,0)) 
  #------Plot-the-figure------    
  plotMap(nepacLL, 
          col=clr$land, 
          bg=clr$sea, 
          xlim=xl, 
          ylim=yl, 
          tck=-0.015,            
          mgp=c(2,.5,0), 
          cex=1.2, 
          plt=c(.08,.98,.08,.98))    
  addPolys(grid_pbs, polyProps=pdata)    
  for (i in 1:nrow(events)) {       
    # plot one point at a time for clarity (seems slow?)      
    points(events$X[i], 
           events$Y[i], 
           pch=16,
           cex=0.50,
           col=clr$white)       
    points(events$X[i], 
           events$Y[i], 
           pch=1, 
           cex=0.55,
           col=clr$black) 
  }
  # title
  yrtxt  <- paste("(",min(events$YEAR),"-",                 
                  substring(max(events$YEAR),3),")",sep="")    
  text(xl[1]+0.1,
       yl[2]-1,
       c("Eastern Bering Sea Hauls\n\n\n", yrtxt),
       cex=1.2,
       adj=0)    
  # add a legend; right-justify the legend labels  
  temp <- legend(x=xl[1]+1, 
                 y=yl[1]+2, 
                 legend = rep(" ", 5),               
                 text.width=strwidth("-1.7 to 13.8 degrees C"), 
                 bty="n", 
                 fill=cols)    
  text(temp$rect$left + temp$rect$w, 
       temp$text$y, 
       pos=2,         
       paste(brks[1:(lbrks-1)],
             brks[2:lbrks], 
             sep=" - "))
  text(temp$rect$left+temp$rect$w/2,
       temp$rect$top,pos=3,
       "Gear Temperatures",
       cex=1);  
}
# call -------------------------------------------------------------------------
makin_plots_dos()
```

```{r, fig.height=12, fig.width=8}
# data -------------------------------------------------------------------------
setup_catch <- read_csv("data/data2/Shelf_Flatfish_Haul_Catch.csv", guess_max = 10000)
setup_catch <- setup_catch %>%
  filter(CRUISE>= 199999 & CRUISE<201900,
         REGION=="BS",
         START_LATITUDE<65) %>%
  mutate(YEAR=floor((CRUISE/100)))
setup_catch <- setup_catch %>% mutate(EID = seq(1:nrow(setup_catch)))
colnames(setup_catch)[14] <- "Y"
colnames(setup_catch)[16] <- "X"
#colnames(setup_catch)[1] <- "EID" doesn't work to change 
# function ---------------------------------------------------------------------
makin_plots_tres <- function() { 
  clr <- .PBSclr(); # load color scheme
  data(nepacLL, envir=sys.frame(sys.nframe())); # load map data
  events <- as.EventData(setup_catch, projection = "LL", zone=3)  #make catch data event data
  # make bounding box
  xl <- c(-179, -157.9); 
  yl <- c(54.1, 65.1)
  # create grid
  grid_pbs   <- makeGrid(x=seq(-179, -157.9), y=seq(54.1, 65.1,1),                     
                     projection="LL", zone=3)    # UTM Zones, Bering Sea is 1-4
  # find Event Data (hauls) in grid and calculate means
  locData<- findCells(events, grid_pbs) 
  events$Z <- events$GEAR_TEMPERATURE # gear_temp is simple to start with 
  # events <- na.omit(events)
  pdata  <- combineEvents(events, locData, FUN=mean,na.rm=TRUE) # summarise step
   # set breakpoints in temps and assign colors
  brks   <- c(-1.6,1.4,4.5,7.5,10.7,13.9);
  lbrks <- length(brks)    
  cols   <- c(clr$lettuce, clr$moss, clr$irish, clr$forest, clr$black) #assign colors to groups
  pdata  <- makeProps(pdata, brks, "col", cols) # append colors column   
  par(mfrow=c(1,1),omi=c(0,0,0,0)) 
  #------Plot-the-figure------    
  plotMap(nepacLL, 
          col=clr$land, 
          bg=clr$sea, 
          xlim=xl, 
          ylim=yl, 
          tck=-0.015,            
          mgp=c(2,.5,0), 
          cex=1.2, 
          plt=c(.08,.98,.08,.98))    
  addPolys(grid_pbs, polyProps=pdata)    
  for (i in 1:nrow(events)) {       
    # plot one point at a time for clarity (seems slow?)      
    points(events$X[i], 
           events$Y[i], 
           pch=16,
           cex=0.50,
           col=clr$white)       
    points(events$X[i], 
           events$Y[i], 
           pch=1, 
           cex=0.55,
           col=clr$black) 
  }
  # title
  yrtxt  <- paste("(",min(events$YEAR),"-",                 
                  substring(max(events$YEAR),3),")",sep="")    
  text(xl[1]+0.1,
       yl[2]-1,
       c("Eastern Bering Sea Hauls\n\n\n", yrtxt),
       cex=1.2,
       adj=0)    
  # add a legend; right-justify the legend labels  
  temp <- legend(x=xl[1]+1, 
                 y=yl[1]+2, 
                 legend = rep(" ", 5),               
                 text.width=strwidth("-1.7 to 13.8 degrees C"), 
                 bty="n", 
                 fill=cols)    
  text(temp$rect$left + temp$rect$w, 
       temp$text$y, 
       pos=2,         
       paste(brks[1:(lbrks-1)],
             brks[2:lbrks], 
             sep=" - "))
  text(temp$rect$left+temp$rect$w/2,
       temp$rect$top,pos=3,
       "Gear Temperatures",
       cex=1);  
}
# call -------------------------------------------------------------------------
makin_plots_tres()
```




