---
title: "Research_Qs_Approaches_Hypotheses_plots"
output: html_notebook
---


```{r load-libraries, warning=FALSE, error=FALSE, message=FALSE}
library(tidyverse)
library(sf)
library(magrittr)
# NOTE: [[[10130=fhs 10210=yfs 10261=nrs(not sp. or juvenile) 10285=akp]]]
```

```{r load-data-and-lowercase, warning=FALSE, error=FALSE, message=FALSE}
make_lowercase <- function(df){
  for (i in 1:length(names(df))){
    names(df)[i] <- tolower(names(df)[i])
  }
  return(df)
}
# load data
catch <- read_csv("data/data2/Shelf_Flatfish_Haul_Catch.csv", guess_max = 10000)
len <- read_csv("data/data2/Shelf_Flatfish_Haul_Catch_length.csv", guess_max = 10000)
spec <- read_csv("data/Shelf_Flatfish_Haul_Specimen.csv", guess_max = 10000)
station_info <- readRDS("data/station_info.rds")
# make all lowercase
catch <- make_lowercase(catch)
len <- make_lowercase(len)
spec <- make_lowercase(spec)
station_info <- make_lowercase(station_info)
```

```{r filter-and-extend-lengths, warning=FALSE, error=FALSE, message=FALSE}
# filter catch
catch <- catch %>%
  filter(cruise>= 199999 & cruise<201900,
         region=="BS") %>%
  mutate(year=floor((cruise/100)))
# filter specimen
hauljoin_list <- unique(catch$hauljoin)
spec <- spec %>%
  filter(hauljoin %in% (hauljoin_list)) %>%
  mutate(year=as.integer(substr(start_time,8,9)))
remove(hauljoin_list)                                   
# filter and extend lengths
len_e <- len %>%
  filter(cruise>= 199999 & cruise<201900,
         region=="BS")%>%
  mutate(year=floor((cruise/100))) %>%
  group_by(hauljoin,species_code) %>%
  mutate(n_subsamp = sum(frequency))%>%
  group_by(hauljoin,species_code, length) %>%
  mutate(ss_prop=(frequency/n_subsamp),
         n_haul = (ss_prop*catch_number_fish))
remove(len)
```

```{r split-up-species, warning=FALSE, error=FALSE, message=FALSE}
# takes interpolated haul lengths and split off a species
separate_spec <- function(spec_code){
  dat <- len_e %>%
    filter(species_code==spec_code)
  return(dat)
}
# divide out species
fhs <- separate_spec(10130)
yfs <- separate_spec(10210)
nrs <- separate_spec(10261)
akp <- separate_spec(10285)

```

```{r create-contour-plots}
plot_contours <- function(df, df_name, y, y_name){
  yvar <- enquo(y)
  df_cut <- df[, c(y_name, "length", "n_haul")]
  df_cut$n_haul %<>% round()
  p <- df %>%
    group_by(length, !!yvar) %>%
    summarise(num =sum(n_haul)) %>%
    uncount(num) %>%
    ggplot()+
    geom_density2d(aes(x=length, y=!!yvar))+
    theme_light()+
    ggtitle(paste(df_name, y_name))
  return(p)
}
p_akp_temp <- plot_contours(akp, "akp", gear_temperature, "gear_temperature")
p_akp_depth <- plot_contours(akp, "akp", bottom_depth, "bottom_depth")
p_fhs_temp <- plot_contours(fhs, "fhs", gear_temperature, "gear_temperature")
p_fhs_depth <- plot_contours(fhs, "fhs", bottom_depth, "bottom_depth")
p_nrs_temp <- plot_contours(fhs, "nrs", gear_temperature, "gear_temperature")
p_nrs_depth <- plot_contours(fhs, "nrs", bottom_depth, "bottom_depth")
p_yfs_temp <- plot_contours(fhs, "yfs", gear_temperature, "gear_temperature")
p_yfs_depth <- plot_contours(fhs, "yfs", bottom_depth, "bottom_depth")
```

```{r}
new_df <- orig_df %>%
  group_by(length, gear_temperature) %>%
  summarise(num =sum(n_haul)) %>%
  uncount(num)

ggplot(new_df)+
  geom_density2d(aes(x=length, y=gear_temperature)) +
    #facet_grid(year~depth_bins, scales="free_x")+
    #geom_vline(aes(xintercept=yr_avg_temp), color="red")+
  theme_light()#+
    # ggtitle(df_name)
```





