---
title: "prior to 09/02/2020"
output: html_notebook
---

```{r libraries}
# load libraries
library(tidyverse)
library(sf)
library(magrittr)

# NOTE: [[[10130=fhs 10210=yfs 10261=nrs(not sp. or juvenile) 10285=akp]]]
```



```{r load data and lowercase}
# so important
make_lowercase <- function(df){
  for (i in 1:length(names(df))){
    names(df)[i] <- tolower(names(df)[i])
  }
  return(df)
}


# load data
catch <- read_csv("data/data2/Shelf_Flatfish_Haul_Catch.csv", guess_max = 10000)
len <- read_csv("data/data2/Shelf_Flatfish_Haul_Catch_length.csv", guess_max = 10000)
# bot <- read_csv("data/bottom_type.csv", guess_max = 10000)
spec <- read_csv("data/Shelf_Flatfish_Haul_Specimen.csv", guess_max = 10000)
station_info <- readRDS("data/station_info.rds")


# make all lowercase
catch <- make_lowercase(catch)
len <- make_lowercase(len)
# bot <- make_lowercase(bot)
spec <- make_lowercase(spec)
station_info <- make_lowercase(station_info)
```



```{r filters}
# filter catch
catch <- catch %>%
  filter(cruise>= 199999 & cruise<201900,
         region=="BS") %>%
  mutate(year=floor((cruise/100)))

# filter specimen
hauljoin_list <- unique(catch$hauljoin) #"copy" filtering from catch data
spec <- spec %>%
  filter(hauljoin %in% (hauljoin_list)) %>%
  mutate(year=as.integer(substr(start_time,8,9)))
remove(hauljoin_list)                                   

# filter and extend lengths
len_e <- len %>%
  filter(cruise>= 199999 & cruise<201900,
         region=="BS")%>%
  mutate(year=floor((cruise/100))) %>%
  group_by(hauljoin,species_code) %>%
  mutate(n_subsamp = sum(frequency))%>%
  group_by(hauljoin,species_code, length) %>%
  mutate(ss_prop=(frequency/n_subsamp),
         n_haul = (ss_prop*catch_number_fish))
remove(len)
```


```{r scatterplot-all-data}
names(len_e)

p1 <- ggplot()+
  geom_point(data=len_e, aes(x=gear_temperature, y=length), alpha=0.01)
p1+geom_smooth(data=len_e, aes(x=gear_temperature, y=length))
```
```{r full-data-boxplot-not-binned}
len_e_factor <- len_e
len_e_factor$length %<>% factor()

p2 <- ggplot()+
  geom_boxplot(data=len_e_factor, aes(x=gear_temperature, y=length))
#p1+geom_smooth(data=len_e, aes(x=gear_temperature, y=length))
p2
```

```{r just-another-full-data-boxplot-binned}
make_length_bins <- function(df){
  sumry <- summary(df$length)
  cuts <- c(sumry[1], sumry[2], sumry[3], sumry[5], sumry[6])
  df$length_bins <- cut(df$length, cuts, include.lowest = TRUE)
  return(df)
}
len_e_bin <- make_length_bins(len_e)

# do for all
# fhs1 <- make_depth_bins(fhs)
# yfs1 <- make_depth_bins(yfs)
# nrs1 <- make_depth_bins(nrs)
# akp1 <- make_depth_bins(akp)
p3 <- ggplot()+
  geom_boxplot(data=len_e_bin, aes(x=gear_temperature, y=length_bins))
#p1+geom_smooth(data=len_e, aes(x=gear_temperature, y=length))
p3
```

```{r split-species-up}
get_spec <- function(spec_code, orig_df){
  dat <- orig_df %>%
    filter(species_code==spec_code)
  return(dat)
}

# do for each species
fhs <- get_spec(10130, len_e)
yfs <- get_spec(10210, len_e)
nrs <- get_spec(10261, len_e)
akp <- get_spec(10285, len_e)
```

```{r bin-lengths-by-species-and-plot}
plot_spec_length_binned <- function(spec_df, name){
  spec_df %>%
    make_length_bins() %>%
    ggplot()+
    geom_boxplot(aes(x=gear_temperature, y=length_bins))+
    ggtitle(name)
}

plot_spec_length_binned(fhs, "fhs")
plot_spec_length_binned(yfs, "yfs")
plot_spec_length_binned(nrs, "nrs")
plot_spec_length_binned(akp, "akp")
```

```{r ind-species-not-binned}
plot_spec_length_f <- function(spec_df, name){
  spec_df %>%
    ggplot()+
    geom_boxplot(aes(x=gear_temperature, y=length))+
    ggtitle(name)
}

fhs_f <- get_spec(10130, len_e_factor)
yfs_f <- get_spec(10210, len_e_factor)
nrs_f <- get_spec(10261, len_e_factor)
akp_f <- get_spec(10285, len_e_factor)

plot_spec_length_f(fhs_f, "fhs")
plot_spec_length_f(yfs_f, "yfs")
plot_spec_length_f(nrs_f, "nrs")
plot_spec_length_f(akp_f, "akp")
```




