---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r libraries}
# load libraries
library(tidyverse)
library(sf)
library(magrittr)

# NOTE: [[[10130=fhs 10210=yfs 10261=nrs(not sp. or juvenile) 10285=akp]]]
```

```{r load data and lowercase}
# so important
make_lowercase <- function(df){
  for (i in 1:length(names(df))){
    names(df)[i] <- tolower(names(df)[i])
  }
  return(df)
}


# load data
catch <- read_csv(".././data/data2/Shelf_Flatfish_Haul_Catch.csv", guess_max = 10000)
len <- read_csv(".././data/data2/Shelf_Flatfish_Haul_Catch_length.csv", guess_max = 10000)
# bot <- read_csv("data/bottom_type.csv", guess_max = 10000)
spec <- read_csv(".././data/Shelf_Flatfish_Haul_Specimen.csv", guess_max = 10000)
station_info <- readRDS(".././data/datapbsmapping/station_info.rds")


# make all lowercase
catch <- make_lowercase(catch)
len <- make_lowercase(len)
# bot <- make_lowercase(bot)
spec <- make_lowercase(spec)
station_info <- make_lowercase(station_info)
```

```{r filters}
# filter catch
catch <- catch %>%
  filter(cruise>= 199999 & cruise<201900,
         region=="BS") %>%
  mutate(year=floor((cruise/100)))

# filter specimen
hauljoin_list <- unique(catch$hauljoin) #"copy" filtering from catch data
spec <- spec %>%
  filter(hauljoin %in% (hauljoin_list)) %>%
  mutate(year=as.integer(substr(start_time,8,9)))
remove(hauljoin_list)                                   

# filter and extend lengths
len_e <- len %>%
  filter(cruise>= 199999 & cruise<201900,
         region=="BS")%>%
  mutate(year=floor((cruise/100))) %>%
  group_by(hauljoin,species_code) %>%
  mutate(n_subsamp = sum(frequency))%>%
  group_by(hauljoin,species_code, length) %>%
  mutate(ss_prop=(frequency/n_subsamp),
         n_haul = (ss_prop*catch_number_fish))
remove(len)
```


```{r sst-plot, fig.height=20, fig.width=14}
#big blue plots (just to look at sst)
ggplot(catch)+
  geom_point(aes(x=start_longitude, y=start_latitude, color=surface_temperature))+
  facet_wrap(~year)+
  theme_minimal()

# check things out
ggplot(station_info)+
  geom_point(aes(x = st_avg_lon, y=st_avg_lat, color=st_avg_depth))+
  theme_light()
```


```{r medians}
# gets the median while accounting for the number of times that a length is repeated per haul
get_median <- function(l, n){
  new_list <- rep(l, round(n))
  return(median(new_list, na.rm = TRUE))
}

# take interpolated haul lengths and try to make them easily plot-able
# by determining medians. then combine with station_info 
get_yrly_st_medians <- function(spec_code){
  dat <- len_e %>%
    filter(species_code==spec_code) %>% # fhs
    group_by(stationid, year, sex) %>% # try including sex?
    summarise(med = get_median(length, n_haul))
  dat <- inner_join(dat, station_info, by="stationid")
  return(dat)
}

# do for each species
fhs <- get_yrly_st_medians(10130)
yfs <- get_yrly_st_medians(10210)
nrs <- get_yrly_st_medians(10261)
akp <- get_yrly_st_medians(10285)
```



```{r depth-bins}
make_depth_bins <- function(df){
  sumry <- summary(df$st_avg_depth)
  cuts <- c(sumry[1], sumry[2], sumry[3], sumry[5], sumry[6])
  df$depth_bins <- cut(df$st_avg_depth, cuts, include.lowest = TRUE)
  return(df)
}

# do for all
fhs1 <- make_depth_bins(fhs)
yfs1 <- make_depth_bins(yfs)
nrs1 <- make_depth_bins(nrs)
akp1 <- make_depth_bins(akp) 

# plot now with facet_grid and depth bins, mostly useless bc just lat/lon (/sanity check)
# ggplot(fhs) + 
#   geom_point(aes(x=st_avg_lon, y=st_avg_lat, color=med)) +
#   facet_grid(year~depth_bins)+
#   theme_light()
```



```{r, density-plots, fig.height=20, fig.width=14}
# plot  with density functions for the medians. pretty boring
large_density_plot <- function(df, df_name){
  ggplot(df)+
    geom_density(aes(x=med))+
    facet_grid(year~depth_bins)+
    theme_light()+
    ggtitle(df_name)
}

large_density_plot(fhs1, "fhs")
large_density_plot(yfs1, "yfs")
large_density_plot(nrs1, "nrs")
large_density_plot(akp1, "akp")
```



```{r}
get_station_avg_temp <- function(df_orig,spec_code){
  df_stat_means <- len_e %>%
    filter(species_code==spec_code) %>%
    group_by(stationid, year) %>%
    summarise(avg_stat_temp = mean(gear_temperature, na.rm = TRUE))
  df_after <- inner_join(df_orig, df_stat_means, by="stationid")
  df_after <- df_after[,-9]
  names(df_after)[2] <- "year"
  return(df_after)
}
fhs2 <- get_station_avg_temp(fhs1,10130)
yfs2 <- get_station_avg_temp(yfs1, 10210)
nrs2 <- get_station_avg_temp(nrs1, 10261)
akp2 <- get_station_avg_temp(akp1, 10285)
```



```{r, get-yr-ref-temps, fig.height=20, fig.width=14}
# make list of the average gear temperature for each year
yearly_avg_temps <- catch %>% 
  group_by(year) %>% 
  summarise(yr_avg_temp = mean(gear_temperature, na.rm=TRUE))

# add that list of average gear temp/year to each df
get_ref_temp <- function(df){
  return(left_join(df, yearly_avg_temps, by="year"))
}
akp3 <- get_ref_temp(akp2)
yfs3 <- get_ref_temp(yfs2)
nrs3 <- get_ref_temp(nrs2)
fhs3 <- get_ref_temp(fhs2)

# so this all isn't great because I've consolidated to the point of
# having lost individual haul temperature data... 
# instead I have the average station temperature data per year
# and then I'm comparing it to the survey average each year
# which is fine but not super useful? 
```



```{r, bad-plots-ref-yr-avgs, fig.height=20, fig.width=14}
plot_stat_temps_and_yr_avgs <- function(df, df_name){
  ggplot(df) + 
    geom_point(aes(x=avg_stat_temp, y=med), alpha=0.1) +
    facet_grid(year~depth_bins, scales="free_x")+
    geom_vline(aes(xintercept=yr_avg_temp), color="red")+
    theme_light()+
    ggtitle(df_name)
}

plot_stat_temps_and_yr_avgs(akp3, "akp")
plot_stat_temps_and_yr_avgs(yfs3, "yfs")
plot_stat_temps_and_yr_avgs(nrs3, "nrs")
plot_stat_temps_and_yr_avgs(fhs3, "fhs")
```



```{r, try-box-plots, fig.height=20, fig.width=14}
plot_box <- function(df, df_name){
  ggplot(df) + 
    geom_smooth(aes(x=avg_stat_temp, y=med), alpha=0.1) +
    facet_grid(year~depth_bins, scales="free_x")+
    geom_vline(aes(xintercept=yr_avg_temp), color="red")+
    theme_light()+
    ggtitle(df_name)
}

plot_box(akp3, "akp")
plot_box(yfs3, "yfs")
plot_box(nrs3, "nrs")
plot_box(fhs3, "fhs")
```


```{r, try-contours, fig.height=40, fig.width=14}
plot_density <- function(df, df_name){
  ggplot(df) + 
    geom_density2d(aes(x=avg_stat_temp, y=med)) +
    facet_grid(year~depth_bins, scales="free_x")+
    geom_vline(aes(xintercept=yr_avg_temp), color="red")+
    theme_light()+
    ggtitle(df_name)
}

plot_density(akp3, "akp")
plot_density(yfs3, "yfs")
plot_density(nrs3, "nrs")
plot_density(fhs3, "fhs")
```

```{r curiosity-about-n-samples-per-yer-per-station}
# ns <- catch %>%
#   count(year, stationid)

summary(ns$n)
ggplot(ns)+
  geom_boxplot(aes(x=n))

ggplot(ns)+
  geom_histogram(aes(x=n), binwidth)+
  coord_cartesian(xlim=c(0, 20))
```



