---
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(PBSmapping)
library(tidyverse)
```

### PBS Mapping Figure 9

```{r}
.PBSfig09()
```

### Data Import

```{r, warnings=FALSE, results="hide", message=FALSE}
setup_catch <- read_csv("data/data2/Shelf_Flatfish_Haul_Catch.csv", guess_max = 10000)
setup_catch <- setup_catch %>%
  filter(CRUISE>= 199999 & CRUISE<201900,
         REGION=="BS", 
         START_LATITUDE<65) %>%
  mutate(YEAR=floor((CRUISE/100)))
setup_catch <- setup_catch %>% mutate(EID = seq(1:nrow(setup_catch)))
colnames(setup_catch)[14] <- "Y"
colnames(setup_catch)[16] <- "X"
#colnames(setup_catch)[1] <- "EID" doesn't work to change 
```

### My Function

```{r, warnings=FALSE, results="hide", message=FALSE}
makin_plots <- function() { 
  clr <- .PBSclr(); # load color scheme
  data(nepacLL, envir=sys.frame(sys.nframe())); # load map data
  events <- as.EventData(setup_catch, projection = "LL", zone=3)  #make catch data event data
  # make bounding box
  xl <- c(-179, -157.9); 
  yl <- c(54.1, 65.1)
  # create grid
  grid_pbs   <- makeGrid(x=seq(-179, -157.9,.5), y=seq(54.1, 65.1,.5),                     
                     projection="LL", zone=3)    # UTM Zones, Bering Sea is 1-4
  # find Event Data (hauls) in grid and calculate means
  locData<- findCells(events, grid_pbs) 
  events$Z <- events$GEAR_TEMPERATURE # gear_temp is simple to start with  
  pdata  <- combineEvents(events, locData, FUN=mean) # summarise step
   # set breakpoints in temps and assign colors
  brks   <- c(-1.7,1.4,4.5,7.5,10.7,13.8);
  lbrks <- length(brks)    
  cols   <- c(clr$lettuce, clr$moss, clr$irish, clr$forest, clr$black) #assign colors to groups
  pdata  <- makeProps(pdata, brks, "col", cols) # append colors column   
  par(mfrow=c(1,1),omi=c(0,0,0,0)) 
  #------Plot-the-figure------    
  plotMap(nepacLL, 
          col=clr$land, 
          bg=clr$sea, 
          xlim=xl, 
          ylim=yl, 
          tck=-0.015,            
          mgp=c(2,.5,0), 
          cex=1.2, 
          plt=c(.08,.98,.08,.98))    
  addPolys(grid_pbs, polyProps=pdata)    
  for (i in 1:nrow(events)) {       
    # plot one point at a time for clarity (seems slow?)      
    points(events$X[i], 
           events$Y[i], 
           pch=16,
           cex=0.50,
           col=clr$white)       
    points(events$X[i], 
           events$Y[i], 
           pch=1, 
           cex=0.55,
           col=clr$black) 
  }
  # title
  yrtxt  <- paste("(",min(events$YEAR),"-",                 
                  substring(max(events$YEAR),3),")",sep="")    
  text(xl[1]+0.1,
       yl[2]-1,
       c("Eastern Bering Sea Hauls\n\n\n", yrtxt),
       cex=1.2,
       adj=0)    
  # add a legend; right-justify the legend labels  
  temp <- legend(x=xl[1]+1, 
                 y=yl[1]+2, 
                 legend = rep(" ", 5),               
                 text.width=strwidth("-1.7 to 13.8 degrees C"), 
                 bty="n", 
                 fill=cols)    
  text(temp$rect$left + temp$rect$w, 
       temp$text$y, 
       pos=2,         
       paste(brks[1:(lbrks-1)],
             brks[2:lbrks], 
             sep=" - "))
  text(temp$rect$left+temp$rect$w/2,
       temp$rect$top,pos=3,
       "Gear Temperatures",
       cex=1);  
}
```

### EBS Data Figure 9

```{r fig.height=16, fig.width=12}
makin_plots()
```

(Something's wrong with the boxes, they should all have points)